### ISSUE TITLE
Unable to run GitHub action

### ISSUE THREAD

**Issue by an-rahulpandey** [microsoft/ApplicationInspector-Action#8]
Hi,
I am not able to run the workflow, getting the error (please see attached image below).
Here is my workflow file - 

```
name: Code Review 
on:
  # Triggers the workflow on pull request events but only for the "main" branch
  pull_request:
    branches: [ "main" ]

jobs:
  check-quality:
    runs-on: ubuntu-latest
    name: A job to check my code quality
    steps:
    - uses: actions/checkout@v2
    - uses: microsoft/ApplicationInspector-Action@v1
    - uses: actions/upload-artifact@v2
      with:
        name: AppInspectorResults
        path: AppInspectorResults.json
```

![workflow-run](https://user-images.githubusercontent.com/2369752/181728537-5d829194-c9f7-472b-9555-fc68c9413cfd.png)

**Comment by gfs** [comment]
Thanks for the report. I'll look into it today.

**Comment by gfs** [comment]
I can't repro this when running your workflow above against the Application Inspector codebase.

I do see an issue here that is not directly related - the progress bar should be disabled in the action so logging messages can hit the output. I'll merge a fix for that today.

![image](https://user-images.githubusercontent.com/98900/181843313-78e391d6-923b-4ad7-ad0a-a089bfbaf032.png)

**Comment by gfs** [comment]
There are a couple possible avenues to identify what might be the issue in your case:

1. You can increase the console verbosity by adding this to the arguments for your AI workflow:

arguments: -x Debug

or 

arguments: -x Verbose

2. You can try running application inspector locally to try to pin down if its an issue with AI itself.
3. If your code is public you can send me a link and I can try to run AI against it and see if anything odd is happening.

**Comment by an-rahulpandey** [comment]
HI @gfs Sorry for replying so late. I ran the verbose command and found this error - 

`[07:32:25 ERR] No pattern matches were detected for files in source path`

I have also created the public repo for it too - 

https://github.com/an-rahulpandey/ionic-react-app

**Comment by gfs** [comment]
No problem. 

Thanks for this additional info. That would seem to indicate that there are no AI detections which match your code. Taking a quick look at it - I'll try myself running against the code you wrote  this week - I'm not sure this Is a bug in the code, we may just not have react specific rules or rules for tsx files.

Even then, it does seem not ideal for it to return an error when there's no matches - and it seems like it does not generate a report (hence the failure in the upload). 

Especially in the context of the action this is bad behavior - I'm not sure that having no findings should really considered an error condition at all.

Thanks, I'll investigate further.

**Comment by gfs** [comment]
I've tested the code you linked with 1.5 locally and it does not have any detections. However, testing with the 1.6 beta it does have successful detection. I suspect something about your code was hitting an issue that I've fixed in between the latest 1.5 and the 1.6 betas.  Once 1.6 is out of beta the action will pick up the new version automatically and it should resolve your issue.  In the meanwhile the workaround would be to use the beta.

I anticipate that the official release of 1.6 will be in the next week or two - depending on the progress of https://github.com/microsoft/DevSkim/pull/390

**Comment by an-rahulpandey** [comment]
Thanks for the update.Will wait for the 1.6 release.
How can I use the beta version in Github action?

**Comment by gfs** [comment]
There is not a way to do this with the existing github action - the arguments don't get passed in until after the docker container is built. But you could easily do this with your own yml. Something like this should work.

```yml
steps:
- uses: actions/checkout@v3
- uses: actions/setup-dotnet@v2
  with:
    dotnet-version: '6.0.x'
- run: dotnet tool install --global Microsoft.CST.ApplicationInspector.CLI --version 1.6.5-beta
- run: appinspector analyze -s path/to/code -f json -o output.json --no-show-progress
- uses: actions/upload-artifact@v3
  with:
    name: app inspector results
    path: output.json
```

**Comment by gfs** [comment]
I updated the Action with a pre-release flag you can try this:

```yml
name: Code Review 
on:
  # Triggers the workflow on pull request events but only for the "main" branch
  pull_request:
    branches: [ "main" ]

jobs:
  check-quality:
    runs-on: ubuntu-latest
    name: A job to check my code quality
    steps:
    - uses: actions/checkout@v2
    - uses: microsoft/ApplicationInspector-Action@v1
      with:
        pre-release: true
    - uses: actions/upload-artifact@v2
      with:
        name: AppInspectorResults
        path: AppInspectorResults.json
```
